### PR TITLE
Add 404 Page and update gitignore

### PR DESCRIPTION
**Pull request by bhavyaagg**

### CODE REVIEW

**Comment by 0xnmn** [comment]
@bhavyaagg .DS_Store is created not just in the root directory but in nested ones too, need to correct the gitignore. Also you will need to remove it from git tracking too. Git won't ignore the already tracked files.

**Comment by bhavyaagg** [comment]
@hereisnaman I have added .DS_Store in the .gitignore without the starting slash(/), so every .DS_Store file will be ignored. And yeah I will have to remove it from the git history. Will do. Thanks.

**Comment by 0xnmn** [comment]
Oh I though it to be folder, cool. Thanks.

**Comment by bhavyaagg** [comment]
I have also removed the .DS_Store file from the tracked changes.

**Review by abhishek97 — APPROVED** [review]

**Pull request merged**
