### PR TITLE
Added Landscape Mode, 100% Responsiveness Achieved

### PR DESCRIPTION
**Pull request by aayusharora**
Video Player:
screen shot 2018-01-03 at 9 57 48 pm
screen shot 2018-01-03 at 9 58 00 pm

 **Final Update** 

Galaxy S5

1.
screen shot 2018-01-10 at 2 32 47 pm
3.
screen shot 2018-01-10 at 2 33 31 pm
4.
screen shot 2018-01-10 at 2 34 04 pm
5.
screen shot 2018-01-10 at 2 34 29 pm
6.
screen shot 2018-01-10 at 2 35 02 pm

### CODE REVIEW

**Comment by witty123** [comment]
fix the external video banner issue as well

**Comment by aayusharora** [comment]
Hi @witty123 Can't reproduce that issue, will you send me a screenshot of it after merging this.

**Comment by witty123** [comment]
@aayusharora 
screen shot 2018-01-04 at 3 19 47 pm
screen shot 2018-01-04 at 3 19 34 pm
The screenshots are of galaxy s5.
Can't merge the current PR since it'll break landscape mode for everyone. Will merge once this is fixed.

**Review by witty123 — CHANGES_REQUESTED** [review]
Fix for external video player banner needed.

**Comment by aayusharora** [comment]
Ok @witty123  Checking this now.

**Review by witty123 — APPROVED** [review]

**Comment by witty123** [comment]
Thanks @aayusharora

**Pull request merged**
